version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: production
  ignore:
  - dependency-name: esbuild
    versions:
    - 0.10.0
    - 0.11.0
    - 0.11.1
    - 0.11.10
    - 0.11.11
    - 0.11.12
    - 0.11.13
    - 0.11.14
    - 0.11.15
    - 0.11.16
    - 0.11.2
    - 0.11.5
    - 0.11.6
    - 0.11.8
    - 0.11.9
    - 0.8.36
    - 0.8.38
    - 0.8.39
    - 0.8.41
    - 0.8.42
    - 0.8.43
    - 0.8.44
    - 0.8.46
    - 0.8.47
    - 0.8.48
    - 0.8.50
    - 0.8.51
    - 0.8.52
    - 0.8.53
    - 0.8.54
    - 0.8.55
    - 0.8.56
    - 0.8.57
    - 0.9.0
    - 0.9.2
    - 0.9.3
    - 0.9.6
    - 0.9.7
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.2.0
