name: test

on: push

jobs:
  build_deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: ['12', '14', '16']
    runs-on: ${{ matrix.os }}
    name: Install, build, and test (OS ${{ matrix.os }} - Node ${{ matrix.node }})
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Test:unit
        run: npm run test

      - name: Test:integration
        run: npm run test:integration
