name: dvlp

on: push

env:
  PNPM_CACHE_FOLDER: .pnpm-store
  HUSKY: 0 # Bypass husky commit hook for CI

jobs:
  build_deploy:
    strategy:
      matrix:
        os: [windows-latest]
        node: ['14']
    runs-on: ${{ matrix.os }}
    name: Install, build, and test (OS ${{ matrix.os }} - Node ${{ matrix.node }})
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: 'Install pnpm'
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.x

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: 'Configure pnpm'
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: 'Install dependencies'
        run: pnpm --frozen-lockfile install

      - name: Build
        run: pnpm run build

      - name: Test:integration
        run: pnpm run test:integration
